name: pr-checks

on: [pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        timeout: 5
        steps:
            - uses: checkout@v3
            - run: npm ci
            - run: npm run lint-js

    test:
        runs-on: ubuntu-latest
        timeout: 10
        steps:
            - uses: checkout@v3
            - run: npm ci
            - run: npm run test-js
