name: test-release-github

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: ./setup-git-identity
      - run: npm ci
      - name: create tag
        run: |-
          git tag -ma v999.9.9
          git push origin v999.9.9
      - id: release
        uses: ./release-github
        with:
          owner: niehusst
          repo: shared-actions
          name: Test Release
          tag: v999.9.9
          body: some body
          assets: './README.md ./LICENSE'
          draft: false
      - name: check release
        run: |-
          release="$(curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/niehusst/shared-actions/releases/${{ steps.release.outputs.id }})"

          set -ex

          tag_name="$(echo "$release" | jq .tag_name)"
          name="$(echo "$release" | jq .name)"
          body="$(echo "$release" | jq .body)"
          draft="$(echo "$release" | jq .draft)"
          asset0="$(echo "$release" | jq .assets[0].name)"
          asset1="$(echo "$release" | jq .assets[1].name)"

          test 'v999.9.9' = $tag_name
          test 'Test Release' = $name
          test 'some body' = $body
          test 'false' = $draft
          test 'README.md' = $asset0 -a 'LICENCE' = $asset1 \
            -o 'README.md' = $asset1 -a 'LICENCE' = $asset0

      - name: delete release
        run: |-
          curl \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/niehusst/shared-actions/releases/${{ steps.release.outputs.id }}
      - name: delete tag
        if: always()
        run: git push --delete origin v999.9.9
