name: 'Update distribution branch'

on:
    push:
        branches:
           - main

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
              with:
                ref: dist
                fetch-depth: 0
            - uses: ./setup-git-identity
            - run: |-
                git fetch origin
                git merge --no-edit origin/main
                npm ci
                cp .gitignore.dist .gitignore
            - uses: ./git-push
              with:
                file_pattern: node_modules
                commit_message: 'ci: update node_modules [ci skip]'
