name: 'Update distribution branch'

on:
    push:
        - branches: [main]

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        timeout: 10
        steps:
            - uses: checkout@v3
              with:
                ref: dist
            - run: |-
                git merge --no-edit origin/main
                npm ci
                cp .gitignore.dist .gitignore
                git add node_modules
                git commit -m "ci: update actions [ci skip]"
                git push origin
