name: 'Update distribution branch'

on:
    push:
        branches:
           - main

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
              with:
                ref: dist
                fetch-depth: 0
            - name: setup git auth
              run: |-
                git config user.name "Liam CI"
                git config user.email "dummy@fakeemail.com"
            - run: |-
                git fetch origin
                git merge --no-edit origin/main
                npm ci
                cp .gitignore.dist .gitignore
                git add .
                git commit -m "ci: update actions [ci skip]"
                git push origin
